require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SuportesController do

  # This should return the minimal set of attributes required to create a valid
  # Suporte. As you add validations to Suporte, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SuportesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all suportes as @suportes" do
      suporte = Suporte.create! valid_attributes
      get :index, {}, valid_session
      assigns(:suportes).should eq([suporte])
    end
  end

  describe "GET show" do
    it "assigns the requested suporte as @suporte" do
      suporte = Suporte.create! valid_attributes
      get :show, {:id => suporte.to_param}, valid_session
      assigns(:suporte).should eq(suporte)
    end
  end

  describe "GET new" do
    it "assigns a new suporte as @suporte" do
      get :new, {}, valid_session
      assigns(:suporte).should be_a_new(Suporte)
    end
  end

  describe "GET edit" do
    it "assigns the requested suporte as @suporte" do
      suporte = Suporte.create! valid_attributes
      get :edit, {:id => suporte.to_param}, valid_session
      assigns(:suporte).should eq(suporte)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Suporte" do
        expect {
          post :create, {:suporte => valid_attributes}, valid_session
        }.to change(Suporte, :count).by(1)
      end

      it "assigns a newly created suporte as @suporte" do
        post :create, {:suporte => valid_attributes}, valid_session
        assigns(:suporte).should be_a(Suporte)
        assigns(:suporte).should be_persisted
      end

      it "redirects to the created suporte" do
        post :create, {:suporte => valid_attributes}, valid_session
        response.should redirect_to(Suporte.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved suporte as @suporte" do
        # Trigger the behavior that occurs when invalid params are submitted
        Suporte.any_instance.stub(:save).and_return(false)
        post :create, {:suporte => {}}, valid_session
        assigns(:suporte).should be_a_new(Suporte)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Suporte.any_instance.stub(:save).and_return(false)
        post :create, {:suporte => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested suporte" do
        suporte = Suporte.create! valid_attributes
        # Assuming there are no other suportes in the database, this
        # specifies that the Suporte created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Suporte.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => suporte.to_param, :suporte => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested suporte as @suporte" do
        suporte = Suporte.create! valid_attributes
        put :update, {:id => suporte.to_param, :suporte => valid_attributes}, valid_session
        assigns(:suporte).should eq(suporte)
      end

      it "redirects to the suporte" do
        suporte = Suporte.create! valid_attributes
        put :update, {:id => suporte.to_param, :suporte => valid_attributes}, valid_session
        response.should redirect_to(suporte)
      end
    end

    describe "with invalid params" do
      it "assigns the suporte as @suporte" do
        suporte = Suporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Suporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => suporte.to_param, :suporte => {}}, valid_session
        assigns(:suporte).should eq(suporte)
      end

      it "re-renders the 'edit' template" do
        suporte = Suporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Suporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => suporte.to_param, :suporte => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested suporte" do
      suporte = Suporte.create! valid_attributes
      expect {
        delete :destroy, {:id => suporte.to_param}, valid_session
      }.to change(Suporte, :count).by(-1)
    end

    it "redirects to the suportes list" do
      suporte = Suporte.create! valid_attributes
      delete :destroy, {:id => suporte.to_param}, valid_session
      response.should redirect_to(suportes_url)
    end
  end

end
